id: P7725102B
initial_creation_type: input
source_metadata:
  Title: 'Saratama: A Panjika on the Astasahasrika Prajnaparamita sutra'
  Editor: Jaini, Padmanabha S.
  Publisher: Kashi Prasad Jayaswal Research Institute
  Place of Publication: Patna
  Year: '1979'
  Sarvākārajñatācaryāparivarto nāma prathamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Śakraparivarto nāma dvitīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aprameyaguṇadhāraṇapāramitāstūpasatkāro nāma tṛtīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Guṇaparikīrtanaparivarto nāma caturthaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Puṇyaparyāyaparivarto nāma pañcamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Anumodanāparimāṇamanāparivarto nāma ṣaṣṭhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Nirayaparivarto nāma saptamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Viśuddhiparivarto nāmāṣṭamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Stutiparivarto nāma navamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dhāraṇaguṇaparikīrtanaparivarto nāma daśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Mārakarmaparivarto nāmaikādaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Lokasaṃdarśanaparivarto nāma dvādaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Trayodaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturdaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Devaparivarto nāma pañcadaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tathatāparivarto nāma ṣoḍaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Avinirvatanīyākāraliṅganimittaparivarto nāma saptadaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Śūnyatāparivarto nāmāṣṭādaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Gaṅgadevābhaginīparivarto nāmekonaviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Upāyakauśalyamīmāṃsāparivarto nāma viṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Mārakarmaparivarto nāmaikaviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Kalyāṇamitraparivarto nāma dvāviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Śakraparivarto nāma trayoviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Abhimānaparivarto nāma catarśititamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Śikṣāparivarto nāma pañcaviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Māyopamaparivarto nāma ṣaḍviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Sāraparivarto nāma saptaviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Avakīrṇakusumaparivarto nāmāṣṭāviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Anugamaparivarto nāmaikonatriṃśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Sadāpraruditaparivarto nāma triṃśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dharmodgataparivarto nāmaikatriśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Parīnandanāparivarto nāma dvātriṃśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:47:11.050635'
last_modified_at: '2022-03-08T16:47:11.050648'
